// This file was generated by Mendix Modeler 6.9.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmqttclient.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TestMqttClient module

	public static String getMQTT_CA()
	{
		return (String)Core.getConfiguration().getConstantValue("TestMqttClient.MQTT_CA");
	}

	public static String getMQTT_CLIENT_CERTIFICATE()
	{
		return (String)Core.getConfiguration().getConstantValue("TestMqttClient.MQTT_CLIENT_CERTIFICATE");
	}

	public static String getMQTT_CLIENT_KEY()
	{
		return (String)Core.getConfiguration().getConstantValue("TestMqttClient.MQTT_CLIENT_KEY");
	}
}