// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testmqttclient.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the TestMqttClient module

	public static java.lang.String getMQTT_CA()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TestMqttClient.MQTT_CA");
	}

	public static java.lang.String getMQTT_CLIENT_CERTIFICATE()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TestMqttClient.MQTT_CLIENT_CERTIFICATE");
	}

	public static java.lang.String getMQTT_CLIENT_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TestMqttClient.MQTT_CLIENT_KEY");
	}

	public static java.lang.String getTTN_APP_PWD()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("TestMqttClient.TTN_APP_PWD");
	}
}