// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttclient.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MqttClient module

	public static String getBROKER_HOST()
	{
		return (String)Core.getConfiguration().getConstantValue("MqttClient.BROKER_HOST");
	}

	public static Long getBROKER_PORT()
	{
		return (Long)Core.getConfiguration().getConstantValue("MqttClient.BROKER_PORT");
	}
}