// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttclient.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MqttClient module

	public static java.lang.String getBROKER_HOST()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MqttClient.BROKER_HOST");
	}

	public static java.lang.Long getBROKER_PORT()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("MqttClient.BROKER_PORT");
	}
}