// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package testmqttclient.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Sleep extends CustomJavaAction<java.lang.Void>
{
	private java.lang.Long Time_ms;

	public Sleep(IContext context, java.lang.Long Time_ms)
	{
		super(context);
		this.Time_ms = Time_ms;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		Thread.sleep(this.Time_ms);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Sleep";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
