// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttHandler;

public class MqttUnsubscribe extends CustomJavaAction<Boolean>
{
	private String BrokerHost;
	private Long BrokerPort;
	private String TopicName;

	public MqttUnsubscribe(IContext context, String BrokerHost, Long BrokerPort, String TopicName)
	{
		super(context);
		this.BrokerHost = BrokerHost;
		this.BrokerPort = BrokerPort;
		this.TopicName = TopicName;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ILogNode logger = Core.getLogger("MqttHandler");
        try {
            MqttHandler handler = new MqttHandler(logger);
            logger.info(String.format("Unsubscribe: %s", this.TopicName));
            handler.unsubscribe(this.BrokerHost, this.BrokerPort, this.TopicName);
            return true;
        } catch (Exception e) {
            return false;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "MqttUnsubscribe";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
