// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mqtt.impl.MqttHandler;

/**
 * 
 */
public class MqttPublish extends CustomJavaAction<Boolean>
{
	private String BrokerHost;
	private Long BrokerPort;
	private String TopicName;
	private String Payload;

	public MqttPublish(IContext context, String BrokerHost, Long BrokerPort, String TopicName, String Payload)
	{
		super(context);
		this.BrokerHost = BrokerHost;
		this.BrokerPort = BrokerPort;
		this.TopicName = TopicName;
		this.Payload = Payload;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        MqttHandler handler = new MqttHandler(Core.getLogger("MqttHandler"));
        try {
            handler.publish(this.BrokerHost, this.BrokerPort, this.TopicName, this.Payload);
            return true;
        } catch (Exception e) {
            return false;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "MqttPublish";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
