// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mqttclient.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mqttclient.impl.MqttHandler;

public class MqttSubscribe extends CustomJavaAction<Boolean>
{
	private String BrokerHost;
	private Long BrokerPort;
	private Long Timeout;
	private String Username;
	private String Password;
	private String TopicName;
	private String OnMessageMicroflow;
	private String CA;
	private String ClientCertificate;
	private String ClientKey;
	private String CertificatePassword;

	public MqttSubscribe(IContext context, String BrokerHost, Long BrokerPort, Long Timeout, String Username, String Password, String TopicName, String OnMessageMicroflow, String CA, String ClientCertificate, String ClientKey, String CertificatePassword)
	{
		super(context);
		this.BrokerHost = BrokerHost;
		this.BrokerPort = BrokerPort;
		this.Timeout = Timeout;
		this.Username = Username;
		this.Password = Password;
		this.TopicName = TopicName;
		this.OnMessageMicroflow = OnMessageMicroflow;
		this.CA = CA;
		this.ClientCertificate = ClientCertificate;
		this.ClientKey = ClientKey;
		this.CertificatePassword = CertificatePassword;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ILogNode logger = Core.getLogger("MqttHandler");
        try {
            MqttHandler handler = new MqttHandler(logger);
            logger.info(String.format("subscribe: %s", this.TopicName));
            handler.subscribe(this.BrokerHost, this.BrokerPort, this.TopicName, this.OnMessageMicroflow, this.CA, this.ClientCertificate, this.ClientKey, this.CertificatePassword, this.Username, this.Password);
            return true;
        } catch (Exception e) {
            return false;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "MqttSubscribe";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
