// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mqttclient.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MqttClient module

	public static boolean mF_Subscribe(IContext context, String _onMessageMicroflow, String _brokerHost, String _topic, Long _brokerPort)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("onMessageMicroflow", _onMessageMicroflow);
			params.put("BrokerHost", _brokerHost);
			params.put("Topic", _topic);
			params.put("BrokerPort", _brokerPort);
			return (Boolean)Core.execute(context, "MqttClient.MF_Subscribe", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}